package com.ce.chat2.participation.entity;

import lombok.*;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;

import java.time.Instant;

@ToString
@Builder
@Setter
@AllArgsConstructor
@NoArgsConstructor
@DynamoDbBean
public class Participation {

    @Getter(onMethod_ = {@DynamoDbPartitionKey, @DynamoDbAttribute("UserId")})
    private Integer userId;

    @Getter(onMethod_ = {@DynamoDbSortKey, @DynamoDbAttribute("RoomId")})
    private String roomId;

    @Getter(onMethod_ = {@DynamoDbAttribute("CreatedAt")})
    private Instant createdAt;

    @Getter(onMethod_ = {@DynamoDbAttribute("UpdatedAt"), @DynamoDbAutoGeneratedTimestampAttribute})
    private Instant updatedAt;

    @Getter(onMethod_ = {@DynamoDbAttribute("IsOut")})
    private boolean isOut;
}
