package com.ce.chat2.participation.entity;

import lombok.*;
import org.springframework.beans.factory.annotation.Value;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.*;

import java.time.Instant;

@ToString
@Builder
@Setter
@AllArgsConstructor
@NoArgsConstructor
@DynamoDbBean
public class Participation {

    @Getter(onMethod_ = {@DynamoDbPartitionKey, @DynamoDbAttribute("UserId"), @DynamoDbSecondarySortKey(indexNames = { "RoomId-UserId-index" })})
    private Integer userId;

    @Getter(onMethod_ = {@DynamoDbSortKey, @DynamoDbAttribute("RoomId"),@DynamoDbSecondaryPartitionKey(indexNames = { "RoomId-UserId-index" }) })
    private String roomId;

    @Getter(onMethod_ = {@DynamoDbAttribute("CreatedAt")}) // @TODO
    private Instant invitedAt;

    @Getter(onMethod_ = {@DynamoDbAttribute("InvitedBy")})
    private Integer invitedBy;

//    @Getter(onMethod_ = {@DynamoDbAttribute("UpdatedAt"), @DynamoDbAutoGeneratedTimestampAttribute})
//    private Instant updatedAt;
//
//    @Getter(onMethod_ = {@DynamoDbAttribute("IsOut")})
//    private boolean isOut;
}
