package com.ce.chat2.participation.entity;

import lombok.Builder;
import lombok.Getter;
import lombok.ToString;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;

import java.time.Instant;

@ToString
@Builder
@DynamoDbBean
public class Participation {

    @Getter(onMethod_ = {@DynamoDbPartitionKey, @DynamoDbAttribute("userId")})
    private String userId;

    @Getter(onMethod_ = {@DynamoDbSortKey, @DynamoDbAttribute("roomId")})
    private String roomId;

    @Getter(onMethod_ = {@DynamoDbAttribute("createdAt")})
    private Instant createdAt;

    @Getter(onMethod_ = {@DynamoDbAttribute("updatedAt"), @DynamoDbAutoGeneratedTimestampAttribute})
    private Instant updatedAt;

    @Getter(onMethod_ = {@DynamoDbAttribute("isOut")})
    private boolean isOut;
}
