package com.ce.chat2.room.entity;

import lombok.*;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;

import java.time.Instant;

@ToString
@Builder
@Setter
@AllArgsConstructor
@NoArgsConstructor
@DynamoDbBean
public class Room {

    @Getter(onMethod_ = {@DynamoDbPartitionKey, @DynamoDbAttribute("roomId")})
    private String roomId;

    @Getter(onMethod_ = {@DynamoDbAttribute("roomName")})
    private String roomName;

    @Getter(onMethod_ = {@DynamoDbAttribute("latestMessage")})
    private String latestMessage;

    @Getter(onMethod_ = {@DynamoDbAttribute("latestTimestamp"), @DynamoDbAutoGeneratedTimestampAttribute})
    private Instant latestTimestamp;

    @Getter(onMethod_ = {@DynamoDbAttribute("createdAt")})
    private Instant createdAt;

}
